### ISSUE TITLE
parameters lab

### ISSUE THREAD

**Issue by lightspeedfitness** [learn-co-curriculum/phase-0-pac-3-function-parameters-lab#16]
### Canvas Link

https://learning.flatironschool.com/courses/6670/assignments/229147?module_item_id=535659

### Concern

this lab is very unclear in terms of the english.  It describes four functions, but the last two have the same name.  Is this the intended effect?  I was able to pass the test, but when I reviewed the testing in the indextest.js file it mentions many other variables. Again if this is the intended behavior, an explanation is at least in order.

### Additional Context

nothing to add

### Suggested Changes

change the name of the fourth function and make sure you cannot pass the test without all four functions. also, clarify the need for the fourth function because the learning objective is not clear.

**Comment by lizbur10** [comment]
Hi @lightspeedfitness! Sometimes it can be helpful to look at the test file if you aren't sure what the tests want you to do, so that's perfectly fine to do. In this case, the test file includes two tests for the same function. What that means is you only need to write one `introductionWithLanguageOptional` function, but it needs to be set up in a way that will pass both tests. 

It can take some time and practice to get the hang of how the tests work. [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) is a great resource if you'd like someone to walk through it with you. The coaches can help you with reading and understanding test output, understanding concepts, debugging code, etc.

Hope this helps! 💙
